import net from "node:net";
import type { EntityName } from "../storage/interface.ts";

export interface ValidationErrorResult {
    valid: boolean;
    error?: string;
    fields?: Record<string, string>;
}

const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const HOSTNAME_REGEX =
    /^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9])(\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9]))*$/;

export function isValidUUID(id: string): boolean {
    return typeof id === "string" && UUID_REGEX.test(id);
}

export function isValidHost(host: string): boolean {
    if (!host || typeof host !== "string") return false;
    if (net.isIP(host)) return true;
    return HOSTNAME_REGEX.test(host);
}

export function validateEntityPayload(
    entity: EntityName,
    payload: any,
    isUpdate = false
): ValidationErrorResult {
    if (!payload || typeof payload !== "object" || Array.isArray(payload)) {
        return { valid: false, error: "Invalid JSON payload" };
    }

    const fields: Record<string, string> = {};

    if ("id" in payload) {
        fields.id = "Cannot supply id; it is generated by the server";
    }
    if ("token" in payload) {
        fields.token = "Cannot supply token; it is generated by the server";
    }
    if ("version" in payload) {
        fields.version = "Cannot supply version; it is read-only";
    }

    if (!isUpdate && !payload.name) {
        fields.name = "Field 'name' is required";
    } else if ("name" in payload) {
        if (
            typeof payload.name !== "string" ||
            payload.name.length < 1 ||
            payload.name.length > 128
        ) {
            fields.name = "Name must be a string between 1 and 128 characters";
        }
    }

    if (entity === "tunnel") {
        if (!isUpdate && !payload.internalHost) {
            fields.internalHost = "Field 'internalHost' is required";
        } else if ("internalHost" in payload) {
            if (!isValidHost(payload.internalHost)) {
                fields.internalHost = "Invalid hostname or IP address";
            }
        }

        if (!isUpdate && payload.internalPort === undefined) {
            fields.internalPort = "Field 'internalPort' is required";
        } else if ("internalPort" in payload) {
            const port = Number(payload.internalPort);
            if (!Number.isInteger(port) || port < 1 || port > 65535) {
                fields.internalPort = "internalPort must be an integer between 1 and 65535";
            }
        }

        if ("edgeId" in payload && payload.edgeId !== null && payload.edgeId !== undefined) {
            if (typeof payload.edgeId !== "string" || !UUID_REGEX.test(payload.edgeId)) {
                fields.edgeId = "Invalid edge identifier";
            }
        }
    }

    if ("metadata" in payload && payload.metadata !== null && payload.metadata !== undefined) {
        if (typeof payload.metadata !== "object" || Array.isArray(payload.metadata)) {
            fields.metadata = "Metadata must be a JSON object";
        } else {
            try {
                const serialized = JSON.stringify(payload.metadata);
                if (Buffer.byteLength(serialized, "utf-8") > 16384) {
                    fields.metadata = "Metadata exceeds maximum size of 16 KB";
                }
            } catch {
                fields.metadata = "Metadata must be serializable JSON";
            }
        }
    }

    if (Object.keys(fields).length > 0) {
        return {
            valid: false,
            error:
                fields.edgeId === "Invalid edge identifier"
                    ? "Invalid edge identifier"
                    : "Validation Error",
            fields,
        };
    }

    return { valid: true };
}
